name: SMPTweaks
version: ${project.version}
main: io.noni.smptweaks.SMPTweaks
api-version: 1.16
authors: [ noniDOTio ]
description: Adds various improvements to make survival minecraft more enjoyable in multiplayer
website: noni.io
